Cities:
    type: entity
    table: cities
    fields:
        cityId:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: city_id
            generator:
                strategy: IDENTITY
        cityName:
            type: string
            length: 128
            fixed: false
            nullable: false
            column: city_name
        cityDescription:
            type: text
            nullable: true
            column: city_description
        cityPostcode:
            type: integer
            unsigned: false
            nullable: false
            column: city_postcode
    manyToOne:
        country:
            targetEntity: Countries
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    referencedColumnName: country_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
