jms_security_extra:
    secure_all_services: false
    expressions: true

parameters: 
  security.encoder.digest.class: SG\FoBundle\Security\MessageDigestPasswordEncoder

security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        SG\FoBundle\Entity\Users:
          algorithm: sha1
          encode_as_base64: true
          #iterations: 5000

    role_hierarchy: 
        District Worker:       District Inhabitant
        City Worker:           District Worker
        Admin:                 City Worker
        Super Admin:           Admin

    providers:
        users:
          entity: { class: SGFoBundle:Users, property: userUsername }
        roles:
          entity: { class: SGFoBundle:Roles, property: roleRolename }

    firewalls:
        secured_area:
          pattern:    ^/
          anonymous: ~
          form_login:
            login_path:  /login
            check_path:  /login_check
            username_parameter: userUsername
            password_parameter: userPassword
          logout:
            path:   /logout
            target: /
          remember_me:
            key:      "%secret%"
            lifetime: 31536000 # 365 days in seconds
            path:     /
            domain:   ~ # Defaults to the current domain from $_SERVER
            remember_me_parameter: remember

 #   access_control:
 #       - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
 #       - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
 #       - { path: ^/logout,   roles: ROLE_USER }
